#############################################################################
# Makefile for building: Anomade
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Dec 22 17:16:29 2011
# Project:  Anomade.pro
# Template: subdirs
# Command: /Volumes/TheBox/QtSDK/Desktop/Qt/474/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o Makefile Anomade.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /Volumes/TheBox/QtSDK/Desktop/Qt/474/gcc/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-libs-MarkdownLib-pro \
		sub-src-AnomadeApp-pro

libs/$(MAKEFILE).MarkdownLib: 
	@$(CHK_DIR_EXISTS) libs/ || $(MKDIR) libs/ 
	cd libs/ && $(QMAKE) /Volumes/TheBox/Repos/anomade/libs/MarkdownLib.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o $(MAKEFILE).MarkdownLib
sub-libs-MarkdownLib-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs/ || $(MKDIR) libs/ 
	cd libs/ && $(QMAKE) /Volumes/TheBox/Repos/anomade/libs/MarkdownLib.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o $(MAKEFILE).MarkdownLib
sub-libs-MarkdownLib-pro: libs/$(MAKEFILE).MarkdownLib FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE).MarkdownLib
sub-libs-MarkdownLib-pro-make_default: libs/$(MAKEFILE).MarkdownLib FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE).MarkdownLib 
sub-libs-MarkdownLib-pro-make_first: libs/$(MAKEFILE).MarkdownLib FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE).MarkdownLib first
sub-libs-MarkdownLib-pro-all: libs/$(MAKEFILE).MarkdownLib FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE).MarkdownLib all
sub-libs-MarkdownLib-pro-clean: libs/$(MAKEFILE).MarkdownLib FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE).MarkdownLib clean
sub-libs-MarkdownLib-pro-distclean: libs/$(MAKEFILE).MarkdownLib FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE).MarkdownLib distclean
sub-libs-MarkdownLib-pro-install_subtargets: libs/$(MAKEFILE).MarkdownLib FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE).MarkdownLib install
sub-libs-MarkdownLib-pro-uninstall_subtargets: libs/$(MAKEFILE).MarkdownLib FORCE
	cd libs/ && $(MAKE) -f $(MAKEFILE).MarkdownLib uninstall
src/$(MAKEFILE).AnomadeApp: 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /Volumes/TheBox/Repos/anomade/src/AnomadeApp.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o $(MAKEFILE).AnomadeApp
sub-src-AnomadeApp-pro-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) /Volumes/TheBox/Repos/anomade/src/AnomadeApp.pro -spec ../../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o $(MAKEFILE).AnomadeApp
sub-src-AnomadeApp-pro: src/$(MAKEFILE).AnomadeApp FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).AnomadeApp
sub-src-AnomadeApp-pro-make_default: src/$(MAKEFILE).AnomadeApp FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).AnomadeApp 
sub-src-AnomadeApp-pro-make_first: src/$(MAKEFILE).AnomadeApp FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).AnomadeApp first
sub-src-AnomadeApp-pro-all: src/$(MAKEFILE).AnomadeApp FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).AnomadeApp all
sub-src-AnomadeApp-pro-clean: src/$(MAKEFILE).AnomadeApp FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).AnomadeApp clean
sub-src-AnomadeApp-pro-distclean: src/$(MAKEFILE).AnomadeApp FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).AnomadeApp distclean
sub-src-AnomadeApp-pro-install_subtargets: src/$(MAKEFILE).AnomadeApp FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).AnomadeApp install
sub-src-AnomadeApp-pro-uninstall_subtargets: src/$(MAKEFILE).AnomadeApp FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE).AnomadeApp uninstall

Makefile: Anomade.pro  ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++/qmake.conf ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o Makefile Anomade.pro
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/474/gcc/mkspecs/macx-g++ -o Makefile Anomade.pro

qmake_all: sub-libs-MarkdownLib-pro-qmake_all sub-src-AnomadeApp-pro-qmake_all FORCE

make_default: sub-libs-MarkdownLib-pro-make_default sub-src-AnomadeApp-pro-make_default FORCE
make_first: sub-libs-MarkdownLib-pro-make_first sub-src-AnomadeApp-pro-make_first FORCE
all: sub-libs-MarkdownLib-pro-all sub-src-AnomadeApp-pro-all FORCE
clean: sub-libs-MarkdownLib-pro-clean sub-src-AnomadeApp-pro-clean FORCE
distclean: sub-libs-MarkdownLib-pro-distclean sub-src-AnomadeApp-pro-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-libs-MarkdownLib-pro-install_subtargets sub-src-AnomadeApp-pro-install_subtargets FORCE
uninstall_subtargets: sub-libs-MarkdownLib-pro-uninstall_subtargets sub-src-AnomadeApp-pro-uninstall_subtargets FORCE

sub-libs-MarkdownLib-pro-check: libs/$(MAKEFILE).MarkdownLib
	cd libs/ && $(MAKE) -f $(MAKEFILE).MarkdownLib check
sub-src-AnomadeApp-pro-check: src/$(MAKEFILE).AnomadeApp
	cd src/ && $(MAKE) -f $(MAKEFILE).AnomadeApp check
check: sub-libs-MarkdownLib-pro-check sub-src-AnomadeApp-pro-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

